name: Build and release OpenAM nightly

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04
    timeout-minutes: 60

    strategy:
      matrix:
        java: [ '8' ]

    env:
      GIT_ORIGIN:           https://github.com/openam-jp
      GIT_BRANCH:           master
      RELEASE_NAME:         nightly
      ARTIFACTS: |
                            ./openam/openam-distribution/openam-distribution-ssoconfiguratortools/target/SSOConfiguratorTools-15.0.0-SNAPSHOT.zip
                            ./openam/openam-distribution/openam-distribution-ssoadmintools/target/SSOAdminTools-15.0.0-SNAPSHOT.zip
                            ./openam/openam-server/target/OpenAM-15.0.0-SNAPSHOT.war
      LICENSE_BODY:         "This project is subject to [the Common Development and Distribution License (CDDL)](LICENSE.md). \
                            Please check all the terms of the license before using these artifacts."
      REPO_NAMES: |
                            forgerock-parent
                            forgerock-bom
                            forgerock-build-tools
                            forgerock-i18n-framework
                            forgerock-guice
                            forgerock-guava
                            forgerock-ui
                            forgerock-commons

    steps:

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.6.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Build in order
      id: build
      run: |
        for REPO in ${REPO_NAMES}; do
          git clone ${GIT_ORIGIN}/${REPO} -b ${GIT_BRANCH}

          #----------------------------------------
          # Ad hoc patch for maven-default-http-blocker
          #----------------------------------------
          if [ "${REPO}" == 'opendj' ]; then
            sed -ie "s|<url>http://download.oracle.com|<url>https://download.oracle.com|g" opendj/opendj-server-legacy/pom.xml
          fi
          if [ "${REPO}" == 'openam' ]; then
            sed -ie "s|<url>http://download.oracle.com|<url>https://download.oracle.com|g" openam/openam-core/pom.xml
          fi
          #----------------------------------------

          mvn clean install -f ${REPO}
          if [ $? -ne 0 ]; then
            exit 1;
          fi
        done

    - name: Test
      id: crest-adapter-test
      run: |
        cd forgerock-commons/rest/json-resource-http
        for i in `seq -w 1 100`; do
          mvn test -Dtest=CrestAdapterTest#shouldWorkWithRealHttpServer
          if [ $? -ne 0 ]; then
            exit 1;
          fi
        done
